<h1>Some sample Data analysis code<h1>

In [2]:
import numpy as np

<p>Some generated values</p>

In [3]:
# Set the random seed to make the examples reproducible
np.random.seed(0)

In [4]:
# An array with a million parameters
m = np.random.randint(10, size=1000000)

def standard_double(array):
    output = np.empty(array.size)
    for i in range(array.size):
        output[i] = array[i] * 2
        
    return output

In [5]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [8]:
a3 = np.ones([1, 4])
a3

array([[1., 1., 1., 1.]])

In [12]:
np.arange(10).mean()

4.5

In [11]:
np.ones((4,4)).sum()

16.0

<h3>Some Pandas Code</h3>

In [14]:
import pandas as pd

In [16]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
s[0]

1

In [18]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [20]:
paid = {
    "Louvre Museum": 5988065,
    "Orsay Museum": 1850092,
    "Pompidou Centre": 2620481,
    "National Natural History Museum": 404497
}

free = {
    "Louvre Museum": 4117897,
    "Orsay Museum": 1436132,
    "Pompidou Centre": 1070337,
    "National Natural History Museum": 344572
}

In [22]:
museum = pd.DataFrame({"paid": paid, "free": free})
museum

paid     free
Louvre Museum                    5988065  4117897
Orsay Museum                     1850092  1436132
Pompidou Centre                  2620481  1070337
National Natural History Museum   404497   344572

In [25]:
museum["paid"]

Louvre Museum                      5988065
Orsay Museum                       1850092
Pompidou Centre                    2620481
National Natural History Museum     404497
Name: paid, dtype: int64

In [26]:
museum[museum["paid"] > 2000000]

paid     free
Louvre Museum    5988065  4117897
Pompidou Centre  2620481  1070337

In [28]:
museum["total"] = museum["free"] + museum["paid"]
museum

paid     free     total
Louvre Museum                    5988065  4117897  10105962
Orsay Museum                     1850092  1436132   3286224
Pompidou Centre                  2620481  1070337   3690818
National Natural History Museum   404497   344572    749069

In [29]:
museum["total"].sum()

17832073

In [30]:
museum["total"].mean()

4458018.25

In [31]:
museums_alternate = pd.read_csv("./museums.csv")
museums_alternate

name     paid     free
0                    Louvre Museum  5988065  4117897
1                     Orsay Museum  1850092  1436132
2                  Pompidou Centre  2620481  1070337
3  National Natural History Museum   404497   344572

In [34]:
museum.to_csv("./museum_converted_to_csv.csv")

<h2>SciKit Learn for some ML</h2>

In [10]:
from sklearn.datasets import load_digits

digits = load_digits()
target = digits.target

data = digits.data
targets = digits.target

print(data[0].reshape((8,8)))
print(targets[0])

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]
0


<p>Gaussian Naive Boyes Model</p>

In [12]:
from sklearn.datasets import load_digits
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

digit2 = load_digits()

data = digits.data
targets = digits.target

# Split into training and testing sets
training_data, testing_data, training_targets, testing_targets = train_test_split(data, targets, random_state=0)

# Train the model
model = GaussianNB()
model.fit(training_data, training_targets)

# Run prediction with the testing set
predicted_targets = model.predict(testing_data)

# Compute the accuracy
accuracy = accuracy_score(testing_targets, predicted_targets)
print(accuracy)

0.8333333333333334


<p>Some sample logic to categorize news groups</p>

In [14]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline


# Load some categories of newsgroups dataset
categories = [
    "soc.religion.christian",
    "talk.religion.misc",
    "comp.sys.mac.hardware",
    "sci.crypt"
]

newsgroups_training = fetch_20newsgroups(
    subset='train',
    categories=categories,
    random_state=0
)

newsgroups_testing = fetch_20newsgroups(
    subset='test', categories=categories, random_state=0
)

In [15]:
newsgroups_training.data[0]

"From: sandvik@newton.apple.com (Kent Sandvik)\nSubject: Re: Ignorance is BLISS, was Is it good that Jesus died?\nOrganization: Cookamunga Tourist Bureau\nLines: 17\n\nIn article <f1682Ap@quack.kfu.com>, pharvey@quack.kfu.com (Paul Harvey)\nwrote:\n> In article <sandvik-170493104859@sandvik-kent.apple.com> \n> sandvik@newton.apple.com (Kent Sandvik) writes:\n> >Ignorance is not bliss!\n \n> Ignorance is STRENGTH!\n> Help spread the TRUTH of IGNORANCE!\n\nHuh, if ignorance is strength, then I won't distribute this piece\nof information if I want to follow your advice (contradiction above).\n\n\nCheers,\nKent\n---\nsandvik@newton.apple.com. ALink: KSAND -- Private activities on the net.\n"