<h1>Some sample Data analysis code<h1>

In [2]:
import numpy as np

<p>Some generated values</p>

In [3]:
# Set the random seed to make the examples reproducible
np.random.seed(0)

In [4]:
# An array with a million parameters
m = np.random.randint(10, size=1000000)

def standard_double(array):
    output = np.empty(array.size)
    for i in range(array.size):
        output[i] = array[i] * 2
        
    return output

In [5]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [8]:
a3 = np.ones([1, 4])
a3

array([[1., 1., 1., 1.]])

In [12]:
np.arange(10).mean()

4.5

In [11]:
np.ones((4,4)).sum()

16.0

<h3>Some Pandas Code</h3>

In [14]:
import pandas as pd

In [16]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
s[0]

1

In [18]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [20]:
paid = {
    "Louvre Museum": 5988065,
    "Orsay Museum": 1850092,
    "Pompidou Centre": 2620481,
    "National Natural History Museum": 404497
}

free = {
    "Louvre Museum": 4117897,
    "Orsay Museum": 1436132,
    "Pompidou Centre": 1070337,
    "National Natural History Museum": 344572
}

In [22]:
museum = pd.DataFrame({"paid": paid, "free": free})
museum

paid     free
Louvre Museum                    5988065  4117897
Orsay Museum                     1850092  1436132
Pompidou Centre                  2620481  1070337
National Natural History Museum   404497   344572

In [25]:
museum["paid"]

Louvre Museum                      5988065
Orsay Museum                       1850092
Pompidou Centre                    2620481
National Natural History Museum     404497
Name: paid, dtype: int64

In [26]:
museum[museum["paid"] > 2000000]

paid     free
Louvre Museum    5988065  4117897
Pompidou Centre  2620481  1070337

In [28]:
museum["total"] = museum["free"] + museum["paid"]
museum

paid     free     total
Louvre Museum                    5988065  4117897  10105962
Orsay Museum                     1850092  1436132   3286224
Pompidou Centre                  2620481  1070337   3690818
National Natural History Museum   404497   344572    749069

In [29]:
museum["total"].sum()

17832073

In [30]:
museum["total"].mean()

4458018.25

In [31]:
museums_alternate = pd.read_csv("./museums.csv")
museums_alternate

name     paid     free
0                    Louvre Museum  5988065  4117897
1                     Orsay Museum  1850092  1436132
2                  Pompidou Centre  2620481  1070337
3  National Natural History Museum   404497   344572

In [34]:
museum.to_csv("./museum_converted_to_csv.csv")

<h2>SciKit Learn for some ML</h2>

In [10]:
from sklearn.datasets import load_digits

digits = load_digits()
target = digits.target

data = digits.data
targets = digits.target

print(data[0].reshape((8,8)))
print(targets[0])

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]
0


<p>Gaussian Naive Boyes Model</p>

In [12]:
from sklearn.datasets import load_digits
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

digit2 = load_digits()

data = digits.data
targets = digits.target

# Split into training and testing sets
training_data, testing_data, training_targets, testing_targets = train_test_split(data, targets, random_state=0)

# Train the model
model = GaussianNB()
model.fit(training_data, training_targets)

# Run prediction with the testing set
predicted_targets = model.predict(testing_data)

# Compute the accuracy
accuracy = accuracy_score(testing_targets, predicted_targets)
print(accuracy)

0.8333333333333334


<p>Some sample logic to categorize news groups</p>

In [14]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline


# Load some categories of newsgroups dataset
categories = [
    "soc.religion.christian",
    "talk.religion.misc",
    "comp.sys.mac.hardware",
    "sci.crypt"
]

newsgroups_training = fetch_20newsgroups(
    subset='train',
    categories=categories,
    random_state=0
)

newsgroups_testing = fetch_20newsgroups(
    subset='test', categories=categories, random_state=0
)

In [15]:
newsgroups_training.data[0]

"From: sandvik@newton.apple.com (Kent Sandvik)\nSubject: Re: Ignorance is BLISS, was Is it good that Jesus died?\nOrganization: Cookamunga Tourist Bureau\nLines: 17\n\nIn article <f1682Ap@quack.kfu.com>, pharvey@quack.kfu.com (Paul Harvey)\nwrote:\n> In article <sandvik-170493104859@sandvik-kent.apple.com> \n> sandvik@newton.apple.com (Kent Sandvik) writes:\n> >Ignorance is not bliss!\n \n> Ignorance is STRENGTH!\n> Help spread the TRUTH of IGNORANCE!\n\nHuh, if ignorance is strength, then I won't distribute this piece\nof information if I want to follow your advice (contradiction above).\n\n\nCheers,\nKent\n---\nsandvik@newton.apple.com. ALink: KSAND -- Private activities on the net.\n"

<p>Pipeline</p>

In [16]:
# Make the pipeline
model = make_pipeline(TfidfVectorizer(), MultinomialNB())

In [20]:
# Train the model
from sklearn.metrics import accuracy_score
model.fit(newsgroups_training.data, newsgroups_training.target)

#Run prediction with the testing set
predicted_targets = model.predict(newsgroups_testing.data)

# Compute the accuracy
accuracy = accuracy_score(newsgroups_testing.target, predicted_targets)
print(accuracy)

# Show the confusion matrix
confusion = confusion_matrix(newsgroups_testing.target, predicted_targets)
confusion_df = pd.DataFrame(confusion, 
    index = pd.Index(newsgroups_testing.target_names, name="True"),
    columns=pd.Index(newsgroups_testing.target_names, name="Predicted")
)

print(confusion_df)

0.8314685314685315
Predicted               comp.sys.mac.hardware  sci.crypt   
True                                                       
comp.sys.mac.hardware                     354         19  \
sci.crypt                                   3        390   
soc.religion.christian                      1          2   
talk.religion.misc                          1         19   

Predicted               soc.religion.christian  talk.religion.misc  
True                                                                
comp.sys.mac.hardware                       12                   0  
sci.crypt                                    3                   0  
soc.religion.christian                     395                   0  
talk.religion.misc                         181                  50  


<p>SciKit Learn Model Validation</p>

In [24]:
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB


digits = load_digits()

data = digits.data
targets = digits.target

# Create the model
model = GaussianNB()

# Run cross-validation
score = cross_val_score(model, data, targets)

print(score)
print(score.mean())

[0.78055556 0.78333333 0.79387187 0.8718663  0.80501393]
0.8069281956050759


<h4>Classifying data with Gaussian Naive Bayes</h4>

In [31]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

digits = load_digits()

data = digits.data
targets = digits.target

# Split into training and testing data sets
training_data, testing_data, training_targets, testing_targets = train_test_split(data, targets, random_state=0)

# Train the model
model = GaussianNB()
model.fit(training_data, training_targets)

# Print the mean and standard deviation of digit 0
print("Mean of each pixel for the  digit 0:")
print(model.theta_[0])
# print("Standard deviation of each pixel for the digit 0:")
# print(model.sigma_[0])

Mean of each pixel for the  digit 0:
[0.00000000e+00 2.83687943e-02 4.12765957e+00 1.29716312e+01
 1.13049645e+01 2.96453901e+00 3.54609929e-02 0.00000000e+00
 0.00000000e+00 9.50354610e-01 1.25035461e+01 1.37021277e+01
 1.16453901e+01 1.12765957e+01 9.00709220e-01 0.00000000e+00
 0.00000000e+00 3.79432624e+00 1.43758865e+01 5.57446809e+00
 2.13475177e+00 1.23049645e+01 3.43971631e+00 0.00000000e+00
 0.00000000e+00 5.31205674e+00 1.27517730e+01 2.06382979e+00
 1.34751773e-01 9.26241135e+00 6.45390071e+00 0.00000000e+00
 0.00000000e+00 5.78723404e+00 1.16737589e+01 1.00000000e+00
 5.67375887e-02 8.89361702e+00 7.10638298e+00 0.00000000e+00
 0.00000000e+00 3.41843972e+00 1.33687943e+01 1.82269504e+00
 1.69503546e+00 1.12127660e+01 5.90070922e+00 0.00000000e+00
 0.00000000e+00 7.80141844e-01 1.29787234e+01 1.02056738e+01
 1.06382979e+01 1.32340426e+01 2.53191489e+00 0.00000000e+00
 0.00000000e+00 7.09219858e-03 4.15602837e+00 1.35602837e+01
 1.33049645e+01 5.46099291e+00 2.83687943e-01 0.

<h4>Support Vector Machines</h4>

In [32]:
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC


digits = load_digits()

data = digits.data
targets = digits.target

#Create the model
model = SVC()

# Run cross validation
score = cross_val_score(model, data, targets)

print(score)
print(score.mean())

[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
0.9632838130609718


<h4>Support Vector Machine Parameters </h4>

In [34]:
from sklearn.datasets import load_digits
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

digits = load_digits()

data = digits.data
targets = digits.target

# Create the grid of parameters
param_grid = {
    "C": [1,10,100,1000],
    "kernel": ["linear","poly", "rbf","sigmoid"]
}

grid = GridSearchCV(SVC(), param_grid)

grid.fit(data, targets)

print("Best Params", grid.best_params_)
print("Best Score", grid.best_score_)

Best Params {'C': 10, 'kernel': 'rbf'}
Best Score 0.9738502011761063


<h4>Dumping a trained model</h4>

In [36]:
import joblib

# Make the pipeline
model = make_pipeline(TfidfVectorizer(), MultinomialNB())

# Train the model
model.fit(newsgroups_training.data, newsgroups_training.target)

# Serialize the model and the target names
model_file = "newsgroups_model.joblib"
model_targets_tuple = (model, newsgroups_training.target_names)
joblib.dump(model_targets_tuple, model_file)

['newsgroups_model.joblib']

<h4>Loading a dumped trained model</h4>

In [38]:
import os
from typing import List, Tuple

import joblib
from sklearn.pipeline import Pipeline


#Load the model
model_file = os.path.join(os.path.dirname(__file__), "newsgroups_model.joblib")
loaded_model: Tuple[Pipeline, List[str]] = joblib.load(model_file)

model, targets = loaded_model

# Run a prediction
p = model.predict(["computer cpu memory ram"])
print(targets[p[0]])

NameError: name '__file__' is not defined